FROM node:16
WORKDIR /app
COPY . /app
RUN cd /app && npm install
RUN cd /app && npm run build
RUN apt-get update && apt-get install apache2 -y
RUN cp -rf /app/build/* /var/www/html/
CMD ["apachectl","-D","FOREGROUND"]
